price = float(input('Цена:'))
discount = float(input('Скидка:'))
vat = float(input('Налог:'))
base = round(price*(1-discount/100),2)
vat_amount = round(base * (vat/100),2)
total = round(base + vat_amount,2)
print(F'База после скидки:{base} ₽')
print(F'НДС:{vat_amount} ₽')
print(F'Итого к оплате:{total} ₽')
