fio = input("ФИО: ")
# fio1 = ' '.join(fio.split())
fio1 = fio.split()
norm_fio = " ".join(fio1)
initial = "".join([x[0].upper() for x in fio1])
print(f"Инициалы: {initial}.")
print(f"Длинна: {len(norm_fio)}")
